### ISSUE TITLE
Better Server Loading Screen

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/friendpardy#100]
Currently, when the app first loads in production (at [friendpardy.onrender.com](https://friendpardy.onrender.com/)), it just says "Connecting to server..." Instead, it should say something like "Server is loading, this may take a minute or two..." and there should be a loading indicator, or a random gif, or something to keep the user's attention. Could even be something like a flappy bird game or other small game. Test it out to see how long it normally takes, and make sure the loading experience matches the time!

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/105
