### ISSUE TITLE
Create Favicon

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendpardy#11]
Currently, the favicon is just a question mark. Create a custom new favicon for Friendpardy.

**Comment by tylerbordeaux** [comment]
![android-chrome-192x192](https://github.com/hto-projects/friendpardy/assets/51490846/ac5104e6-2e14-4c37-8e82-0f57a800ccbb)
Idea

**Comment by tylerbordeaux** [comment]
![Image](https://github.com/hto-projects/friendpardy/assets/51490846/ccc67397-eaff-4cc8-ad62-89c2e16a0607)

By Andrew
