### ISSUE TITLE
Bug: Leaderboard sorts incorrectly

### ISSUE THREAD

**Issue by Arrowship06** [hto-projects/friendpardy#111]
When you get to the leaderboard it is sorted from lowest to highest rather than highest to lowest. 
![Image](https://github.com/hto-projects/friendpardy/assets/102868134/b7819285-91a7-425f-9d24-49d7ac64e4a3)

**Comment by tylerbordeaux** [comment]
Fixed https://github.com/hto-projects/friendpardy/pull/109/commits/8740bb65340a4482110a1ac0593451b6a01929d5
