### ISSUE TITLE
Host Lobby: Larger Player Cards

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendpardy#12]
Currently, when the Host is in the Lobby, the players are displayed in a bulleted list. This works, but it does not look too good. Update the page so that all the names show up larger, and in a layout of cards. The [MUI Paper](https://mui.com/material-ui/react-paper/) element may be helpful for this.

It could end up looking something like this:

![Image](https://github.com/hto-projects/friendpardy/assets/43472480/bd2aeeca-1cd8-48da-aef1-fb811a40b7e0)

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/55
