### ISSUE TITLE
Questions not matching host and join

### ISSUE THREAD

**Issue by tylerbordeaux** [hto-projects/friendpardy#140]

**Comment by tylerbordeaux** [comment]
Also, random questions does not deal with duplicates

**Comment by Arrowship06** [comment]
What do you mean?

**Comment by tylerbordeaux** [comment]
I meant that the same question could appear twice in the questionnaire

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/147
