### ISSUE TITLE
Host Questionnaire: Player Progress

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendpardy#15]
Currently, during the questionnaire portion, the Host screen simply displays a message saying everyone is working on the questionnaire. This should be more dynamic: it should display which players are still working on the questionnaire, and which players are done with the questionnaire.

To do this, it will be necessary to access the status of each player. The host screen should update any time a player submits a questionnaire, and the data should be sent when the page is refreshed as well.

**Comment by tylerbordeaux** [comment]
Works but only updates on reload https://github.com/hto-projects/friendpardy/tree/player-progress

**Comment by tylerbordeaux** [comment]
Working on adding kicking now

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/257
