### ISSUE TITLE
Host Quiz Answer: show point updates for players

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/friendpardy#158]

**Comment by tylerbordeaux** [comment]
![Image](https://github.com/hto-projects/friendpardy/assets/51490846/6493d088-1157-4344-b5f2-074edd006163)

**Comment by tylerbordeaux** [comment]
![Image](https://github.com/hto-projects/friendpardy/assets/51490846/cf454ad2-44b2-4139-b9d8-c7ddadb36b39)
