### ISSUE TITLE
Player Quiz Answer: show point updates, and turn screen green if question was answered correctly

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/friendpardy#159]

**Comment by tylerbordeaux** [comment]
Correct screen: 
<img width="390" alt="Screenshot 2023-07-11 at 12 43 17 PM" src="https://github.com/hto-projects/friendpardy/assets/51490846/49e67b05-fb46-4403-84ec-301f2123eea1">

**Comment by tylerbordeaux** [comment]
Incorrect screen: 
<img width="365" alt="Screenshot 2023-07-11 at 12 49 43 PM" src="https://github.com/hto-projects/friendpardy/assets/51490846/2a622b6f-0d73-4985-b17a-86dd55e0a8eb">

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/167
