### ISSUE TITLE
Host Lobby: No Games with <2 Players

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendpardy#18]
Currently it is possible to start a game with as little as 0 players. The game doesn't really make any sense unless there are at least two players... it would probably be a lot more fun with at least four, but 2 would be the bare minimum.

Prevent the host from starting a game unless there are at least two players. This should be verified on both the front-end AND the back-end.

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/74
