### ISSUE TITLE
When host mutes music during game it resets question timer

### ISSUE THREAD

**Issue by Arrowship06** [hto-projects/friendpardy#260]
While playing a game I muted the music. When the timer ran down it stayed at zero until toggling mute or clicking show answers. When you click the toggle mute button the timer resets to 15 (Have not tested on non-defualt settings). Going to the next question works. 
Edit: the timer not working is a separate issue

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/264
