### ISSUE TITLE
Typo: Player Questionnaire Page

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendpardy#3]
When the game has been started and a player is on the Questionnaire page, the word "question" is mispelled:

![Image](https://github.com/hto-projects/friendpardy/assets/43472480/337300b4-ddba-48ad-9d71-4e4e529248eb)

**Comment by karthickbharathi1** [comment]
I have fixed the issue.

**Comment by Arrowship06** [comment]
That line of text does not exist anymore
