### ISSUE TITLE
Do not allow a player to answer if the quiz question is about them

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendpardy#45]
Currently, when the quiz portion begins, all players are able to answer each question. For example, if the quiz question was **What is Michael's favorite movie?**, everybody would be able to answer - including Michael. Michael obviously knows the answer, so Michael should not be allowed to get any points.

Basically, the player to whom the question pertains should be directly moved to the `PlayerStates.QuestionAboutMe` state, and should see a message saying something like "Wait while the other players answer this question about you!"

Some things that will need to change:

- The `allPlayersGoToNextQuestion` function will need to be altered so that the player to whom the question refers is set to the `QuestionAboutMe` state, instead of the `SeeingQuestion` state
- The `checkAllPlayersAnsweredQuizQuestion` function will need to be altered so that it checks to see if a player is in the `AnsweredQuizQuestionWaiting` state, _or_ the `QuestionAboutMe` state.

There may be additional changes required as well.

**Comment by tylerbordeaux** [comment]
This functionality is working, but for some reason answer choice clicks are not registering for users who are supposed to answer.

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/95
