### ISSUE TITLE
Typo: Host Questionnaire Page

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendpardy#6]
When hosting the game, after starting it, on the Questionnaire page, the word "compete" should be "complete" instead:

![Image](https://user-images.githubusercontent.com/43472480/244107967-d8fca9fb-661a-46cf-ae79-532f3ee992f4.png)

**Comment by karthickbharathi1** [comment]
I fixed the issue

**Comment by tylerbordeaux** [comment]
Fixed, branch is ready to merge!
