### ISSUE TITLE
Figure out a Tiebreaker

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/friendpardy#78]
It is currently possible for two players to have the same score at the end of the game.

Potentially add a modifier for answering speed on each question so that every player always has a different score... or add a final tiebreaker round where the winner is based on speed or something

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/214

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/214
