### ISSUE TITLE
Typo: Host Lobby Page

### ISSUE THREAD

**Issue by hylandtechoutreach** [hto-projects/friendpardy#8]
After hosting a new game and opening the lobby, it says "These player have joined the game" when it should say "These _players_ have joined the game" instead:

![Image](https://user-images.githubusercontent.com/43472480/244109694-afbf9dd3-f6c0-40bb-805e-ac329ea8ee1b.png)

**Comment by karthickbharathi1** [comment]
I can solve this issue.
