### ISSUE TITLE
Fix Socket ID Storage for Players

### ISSUE THREAD

**Issue by josephmaxwellhyland** [hto-projects/friendpardy#96]
Currently, if a player refreshes the page, it looks like they connect with a new socket id. The player's socket id stored in the database should be updated every time a refresh happens, so it reflects the most recent connection.

I believe this should happen in the `onPlayerLoad` function, in the **playerHandler.ts** file.

**Comment by tylerbordeaux** [comment]
https://github.com/hto-projects/friendpardy/pull/106
